"use client";
import { useState } from "react";
import Link from "next/link";
import { mockMaintenanceTasks, mockEquipment } from "@/lib/mockData";
import { Card, PageHeader, PriorityBadge } from "@/components/ui";
import type { MaintenanceTask } from "@/lib/api";

type PF = "ALL"|"CRITICAL"|"HIGH"|"MEDIUM"|"LOW";
type SF = "ALL"|"PENDING"|"IN_PROGRESS"|"COMPLETED";
const prioOrder = { CRITICAL:0, HIGH:1, MEDIUM:2, LOW:3 };

export default function MaintenancePage() {
  const [pf, setPf] = useState<PF>("ALL");
  const [sf, setSf] = useState<SF>("PENDING");
  const [tasks, setTasks] = useState<MaintenanceTask[]>(mockMaintenanceTasks);

  const visible = tasks
    .filter((t) => pf==="ALL" || t.priority===pf)
    .filter((t) => sf==="ALL" || t.status===sf)
    .sort((a,b) => prioOrder[a.priority]-prioOrder[b.priority]);

  const model = (id: string) => mockEquipment.find(e=>e.equipment_id===id)?.model ?? id;
  const totalDT = visible.reduce((s,t)=>s+t.estimated_downtime,0);

  return (
    <div className="p-6 max-w-5xl mx-auto">
      <PageHeader title="Maintenance Recommendations" subtitle="Prioritised tasks generated by the AI prediction engine" />

      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-5">
        {(["CRITICAL","HIGH","MEDIUM","LOW"] as const).map((p) => {
          const count = tasks.filter(t=>t.priority===p && t.status!=="COMPLETED").length;
          return (
            <Card key={p} className="text-center py-3">
              <p className="text-xs text-slate-400 uppercase tracking-wide">{p}</p>
              <p className={`text-2xl font-bold mt-0.5 ${p==="CRITICAL"?"text-red-600":p==="HIGH"?"text-orange-500":p==="MEDIUM"?"text-yellow-600":"text-slate-500"}`}>{count}</p>
            </Card>
          );
        })}
      </div>

      <div className="flex gap-2 flex-wrap mb-5">
        {(["ALL","CRITICAL","HIGH","MEDIUM","LOW"] as PF[]).map((p) => (
          <button key={p} onClick={()=>setPf(p)} className={`px-3 py-1 rounded-full text-xs font-medium border transition-colors ${pf===p?"bg-slate-800 text-white border-slate-800":"bg-white text-slate-500 border-slate-200 hover:border-slate-400"}`}>{p}</button>
        ))}
        <span className="mx-2 text-slate-200">|</span>
        {(["ALL","PENDING","IN_PROGRESS","COMPLETED"] as SF[]).map((s) => (
          <button key={s} onClick={()=>setSf(s)} className={`px-3 py-1 rounded-full text-xs font-medium border transition-colors ${sf===s?"bg-slate-800 text-white border-slate-800":"bg-white text-slate-500 border-slate-200 hover:border-slate-400"}`}>{s.replace("_"," ")}</button>
        ))}
      </div>

      {visible.length===0 && <Card><p className="text-sm text-slate-400 text-center py-8">No tasks match the selected filters.</p></Card>}
      <div className="space-y-3">
        {visible.map((t) => (
          <div key={t.task_id} className={`bg-white rounded-xl border shadow-sm p-4 flex gap-4 ${t.status==="COMPLETED"?"opacity-50":""}`}>
            <div className={`w-1 rounded-full self-stretch ${t.priority==="CRITICAL"?"bg-red-500":t.priority==="HIGH"?"bg-orange-400":t.priority==="MEDIUM"?"bg-yellow-400":"bg-slate-300"}`} />
            <div className="flex-1 min-w-0">
              <div className="flex items-start gap-2 justify-between flex-wrap">
                <div>
                  <p className="text-sm font-semibold text-slate-800">{t.task_type}</p>
                  <p className="text-xs text-slate-400 mt-0.5">
                    <Link href={`/equipment/${t.equipment_id}`} className="text-blue-600 hover:underline font-medium">{t.equipment_id}</Link> · {model(t.equipment_id)} · {t.component_id}
                  </p>
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  <PriorityBadge priority={t.priority} />
                  <span className={`text-xs px-2 py-0.5 rounded border font-medium ${t.status==="COMPLETED"?"bg-emerald-50 text-emerald-700 border-emerald-200":t.status==="IN_PROGRESS"?"bg-blue-50 text-blue-700 border-blue-200":"bg-slate-50 text-slate-600 border-slate-200"}`}>
                    {t.status.replace("_"," ")}
                  </span>
                </div>
              </div>
              <p className="text-sm text-slate-600 mt-2 leading-relaxed">{t.recommended_action}</p>
              <div className="flex items-center gap-4 mt-3">
                <span className="text-xs text-slate-400">⏱ Est. downtime: {t.estimated_downtime}h</span>
                {t.status==="PENDING" && <button onClick={()=>setTasks(p=>p.map(x=>x.task_id===t.task_id?{...x,status:"IN_PROGRESS"}:x))} className="text-xs text-blue-600 hover:underline font-medium">Start →</button>}
                {t.status==="IN_PROGRESS" && <button onClick={()=>setTasks(p=>p.map(x=>x.task_id===t.task_id?{...x,status:"COMPLETED"}:x))} className="text-xs text-emerald-600 hover:underline font-medium">Mark Complete ✓</button>}
              </div>
            </div>
          </div>
        ))}
      </div>
      {visible.length>0 && <p className="mt-4 text-xs text-slate-400 text-right">{visible.length} tasks · Total est. downtime: <strong>{totalDT}h</strong></p>}
    </div>
  );
}
